name: Terraform Multicloud Deployment

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  validation:
    name: Validation Terraform
    runs-on: ubuntu-latest

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurer les identifiants AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialisation Terraform
        run: terraform init

      - name: Vérification du format Terraform
        run: terraform fmt -check

      - name: Validation Terraform
        run: terraform validate


  security:
    name: Analyse sécurité Checkov
    runs-on: ubuntu-latest
    needs: validation

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification fichier EC2
        run: cat modules/aws/ec2/main.tf

      - name: Installation Checkov
        run: pip install checkov

      - name: Scan sécurité Terraform
        run: checkov -d . --config-file .checkov.yml


  deploy:
    name: Déploiement Terraform AWS
    runs-on: ubuntu-latest

    needs:
      - validation
      - security

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurer les identifiants AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialisation Terraform
        run: terraform init

      - name: Déploiement Terraform
        run: terraform apply -auto-approve


  ansible:
    name: Configuration Ansible
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:

      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Configuration de la clé SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/galion-devops-key.pem
          chmod 400 ~/.ssh/galion-devops-key.pem
          ssh-keygen -y -f ~/.ssh/galion-devops-key.pem > /dev/null

      - name: Exécution du playbook Ansible
        working-directory: ansible
        run: |
          ansible-playbook playbook.yml


  tests:
    name: Tests du déploiement
    runs-on: ubuntu-latest

    needs:
      - ansible

    steps:

      - name: Test accessibilité serveur web
        run: |
          curl -f http://100.53.85.65

      - name: Vérification contenu page web
        run: |
          curl -f http://100.53.85.65 | grep "Terraform + Ansible AWS deployment successful"
